import { useEffect, useState } from 'react';
import { MapContainer, TileLayer, Polyline, Marker, useMap } from 'react-leaflet';
import L from 'leaflet';
import { Navigation } from 'lucide-react';
import { Button } from '@/components/ui/button';
const path:[[number,number],[number,number],[number,number],[number,number]]=[[-25.4753,30.9702],[-25.4737,30.9736],[-25.4710,30.9765],[-25.4687,30.9798]];
const bikeIcon=L.divIcon({className:'',html:'<div style="background:#E10600;color:white;border:3px solid white;border-radius:50%;width:40px;height:40px;display:grid;place-items:center;font-size:20px;box-shadow:0 0 20px #E10600">🏍</div>',iconSize:[40,40],iconAnchor:[20,20]});
const pinIcon=L.divIcon({className:'',html:'<div style="color:#E10600;font-size:34px;text-shadow:0 2px 8px black">●</div>',iconSize:[34,34]});
function Follow({position,follow}:{position:[number,number];follow:boolean}){const map=useMap();useEffect(()=>{if(follow) map.flyTo(position,15,{duration:1.4})},[position,follow,map]);return null}
export function TransferMap({active,driverLocation}:{active:boolean;driverLocation:{lat:number;lng:number}|undefined}){const [step,setStep]=useState(0);const [follow,setFollow]=useState(false);useEffect(()=>{if(!active)return;const interval=setInterval(()=>setStep(n=>(n+1)%12),3000);return()=>clearInterval(interval)},[active]);const seg=Math.floor(step/4);const f=(step%4)/4;const a=path[Math.min(seg,2)]??path[0],b=path[Math.min(seg+1,3)]??path[3];const position:[number,number]=[a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f];return <div className="map-dark relative h-[50vh] min-h-[350px] overflow-hidden"><MapContainer center={[-25.472,30.975]} zoom={14} scrollWheelZoom className="h-full w-full"><TileLayer attribution="© OpenStreetMap" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Polyline positions={path} pathOptions={{color:'#ff6b00',weight:6,opacity:.9}}/><Marker position={path[3]} icon={pinIcon}/><Marker position={driverLocation?[driverLocation.lat,driverLocation.lng]:position} icon={bikeIcon}/><Follow position={driverLocation?[driverLocation.lat,driverLocation.lng]:position} follow={follow}/></MapContainer><Button onClick={()=>setFollow(!follow)} className="red-gradient absolute bottom-5 right-5 z-[500] h-11 rounded-full"><Navigation size={17}/> {follow?'Following rider':'Live Tracking'}</Button></div>}
