/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ClientHomeRouteImport } from './routes/client-home'
import { Route as DriverControlCenterRouteImport } from './routes/driver-control-center'
import { Route as DriverDashboardRouteImport } from './routes/driver-dashboard'
import { Route as DriverHomeRouteImport } from './routes/driver-home'
import { Route as FoodOrderFormRouteImport } from './routes/food-order-form'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrderHistoryRouteImport } from './routes/order-history'
import { Route as PartnerDashboardRouteImport } from './routes/partner-dashboard'
import { Route as PaxiFormRouteImport } from './routes/paxi-form'
import { Route as PaxiReceiveRouteImport } from './routes/paxi-receive'
import { Route as PaxiSendRouteImport } from './routes/paxi-send'
import { Route as ReceiveParcelFormRouteImport } from './routes/receive-parcel-form'
import { Route as RequestTypeRouteImport } from './routes/request-type'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SendParcelFormRouteImport } from './routes/send-parcel-form'
import { Route as TrackOrderRouteImport } from './routes/track-order'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientHomeRoute = ClientHomeRouteImport.update({
  id: '/client-home',
  path: '/client-home',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverControlCenterRoute = DriverControlCenterRouteImport.update({
  id: '/driver-control-center',
  path: '/driver-control-center',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/driver-dashboard',
  path: '/driver-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverHomeRoute = DriverHomeRouteImport.update({
  id: '/driver-home',
  path: '/driver-home',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodOrderFormRoute = FoodOrderFormRouteImport.update({
  id: '/food-order-form',
  path: '/food-order-form',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderHistoryRoute = OrderHistoryRouteImport.update({
  id: '/order-history',
  path: '/order-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner-dashboard',
  path: '/partner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PaxiFormRoute = PaxiFormRouteImport.update({
  id: '/paxi-form',
  path: '/paxi-form',
  getParentRoute: () => rootRouteImport,
} as any)
const PaxiReceiveRoute = PaxiReceiveRouteImport.update({
  id: '/paxi-receive',
  path: '/paxi-receive',
  getParentRoute: () => rootRouteImport,
} as any)
const PaxiSendRoute = PaxiSendRouteImport.update({
  id: '/paxi-send',
  path: '/paxi-send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveParcelFormRoute = ReceiveParcelFormRouteImport.update({
  id: '/receive-parcel-form',
  path: '/receive-parcel-form',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestTypeRoute = RequestTypeRouteImport.update({
  id: '/request-type',
  path: '/request-type',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SendParcelFormRoute = SendParcelFormRouteImport.update({
  id: '/send-parcel-form',
  path: '/send-parcel-form',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-home': typeof ClientHomeRoute
  '/driver-control-center': typeof DriverControlCenterRoute
  '/driver-dashboard': typeof DriverDashboardRoute
  '/driver-home': typeof DriverHomeRoute
  '/food-order-form': typeof FoodOrderFormRoute
  '/login': typeof LoginRoute
  '/order-history': typeof OrderHistoryRoute
  '/partner-dashboard': typeof PartnerDashboardRoute
  '/paxi-form': typeof PaxiFormRoute
  '/paxi-receive': typeof PaxiReceiveRoute
  '/paxi-send': typeof PaxiSendRoute
  '/receive-parcel-form': typeof ReceiveParcelFormRoute
  '/request-type': typeof RequestTypeRoute
  '/reviews': typeof ReviewsRoute
  '/send-parcel-form': typeof SendParcelFormRoute
  '/track-order': typeof TrackOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-home': typeof ClientHomeRoute
  '/driver-control-center': typeof DriverControlCenterRoute
  '/driver-dashboard': typeof DriverDashboardRoute
  '/driver-home': typeof DriverHomeRoute
  '/food-order-form': typeof FoodOrderFormRoute
  '/login': typeof LoginRoute
  '/order-history': typeof OrderHistoryRoute
  '/partner-dashboard': typeof PartnerDashboardRoute
  '/paxi-form': typeof PaxiFormRoute
  '/paxi-receive': typeof PaxiReceiveRoute
  '/paxi-send': typeof PaxiSendRoute
  '/receive-parcel-form': typeof ReceiveParcelFormRoute
  '/request-type': typeof RequestTypeRoute
  '/reviews': typeof ReviewsRoute
  '/send-parcel-form': typeof SendParcelFormRoute
  '/track-order': typeof TrackOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-home': typeof ClientHomeRoute
  '/driver-control-center': typeof DriverControlCenterRoute
  '/driver-dashboard': typeof DriverDashboardRoute
  '/driver-home': typeof DriverHomeRoute
  '/food-order-form': typeof FoodOrderFormRoute
  '/login': typeof LoginRoute
  '/order-history': typeof OrderHistoryRoute
  '/partner-dashboard': typeof PartnerDashboardRoute
  '/paxi-form': typeof PaxiFormRoute
  '/paxi-receive': typeof PaxiReceiveRoute
  '/paxi-send': typeof PaxiSendRoute
  '/receive-parcel-form': typeof ReceiveParcelFormRoute
  '/request-type': typeof RequestTypeRoute
  '/reviews': typeof ReviewsRoute
  '/send-parcel-form': typeof SendParcelFormRoute
  '/track-order': typeof TrackOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/client-home'
    | '/driver-control-center'
    | '/driver-dashboard'
    | '/driver-home'
    | '/food-order-form'
    | '/login'
    | '/order-history'
    | '/partner-dashboard'
    | '/paxi-form'
    | '/paxi-receive'
    | '/paxi-send'
    | '/receive-parcel-form'
    | '/request-type'
    | '/reviews'
    | '/send-parcel-form'
    | '/track-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/client-home'
    | '/driver-control-center'
    | '/driver-dashboard'
    | '/driver-home'
    | '/food-order-form'
    | '/login'
    | '/order-history'
    | '/partner-dashboard'
    | '/paxi-form'
    | '/paxi-receive'
    | '/paxi-send'
    | '/receive-parcel-form'
    | '/request-type'
    | '/reviews'
    | '/send-parcel-form'
    | '/track-order'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/client-home'
    | '/driver-control-center'
    | '/driver-dashboard'
    | '/driver-home'
    | '/food-order-form'
    | '/login'
    | '/order-history'
    | '/partner-dashboard'
    | '/paxi-form'
    | '/paxi-receive'
    | '/paxi-send'
    | '/receive-parcel-form'
    | '/request-type'
    | '/reviews'
    | '/send-parcel-form'
    | '/track-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClientHomeRoute: typeof ClientHomeRoute
  DriverControlCenterRoute: typeof DriverControlCenterRoute
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverHomeRoute: typeof DriverHomeRoute
  FoodOrderFormRoute: typeof FoodOrderFormRoute
  LoginRoute: typeof LoginRoute
  OrderHistoryRoute: typeof OrderHistoryRoute
  PartnerDashboardRoute: typeof PartnerDashboardRoute
  PaxiFormRoute: typeof PaxiFormRoute
  PaxiReceiveRoute: typeof PaxiReceiveRoute
  PaxiSendRoute: typeof PaxiSendRoute
  ReceiveParcelFormRoute: typeof ReceiveParcelFormRoute
  RequestTypeRoute: typeof RequestTypeRoute
  ReviewsRoute: typeof ReviewsRoute
  SendParcelFormRoute: typeof SendParcelFormRoute
  TrackOrderRoute: typeof TrackOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-home': {
      id: '/client-home'
      path: '/client-home'
      fullPath: '/client-home'
      preLoaderRoute: typeof ClientHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-control-center': {
      id: '/driver-control-center'
      path: '/driver-control-center'
      fullPath: '/driver-control-center'
      preLoaderRoute: typeof DriverControlCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-dashboard': {
      id: '/driver-dashboard'
      path: '/driver-dashboard'
      fullPath: '/driver-dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-home': {
      id: '/driver-home'
      path: '/driver-home'
      fullPath: '/driver-home'
      preLoaderRoute: typeof DriverHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-order-form': {
      id: '/food-order-form'
      path: '/food-order-form'
      fullPath: '/food-order-form'
      preLoaderRoute: typeof FoodOrderFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-history': {
      id: '/order-history'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof OrderHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-dashboard': {
      id: '/partner-dashboard'
      path: '/partner-dashboard'
      fullPath: '/partner-dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paxi-form': {
      id: '/paxi-form'
      path: '/paxi-form'
      fullPath: '/paxi-form'
      preLoaderRoute: typeof PaxiFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paxi-receive': {
      id: '/paxi-receive'
      path: '/paxi-receive'
      fullPath: '/paxi-receive'
      preLoaderRoute: typeof PaxiReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paxi-send': {
      id: '/paxi-send'
      path: '/paxi-send'
      fullPath: '/paxi-send'
      preLoaderRoute: typeof PaxiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive-parcel-form': {
      id: '/receive-parcel-form'
      path: '/receive-parcel-form'
      fullPath: '/receive-parcel-form'
      preLoaderRoute: typeof ReceiveParcelFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-type': {
      id: '/request-type'
      path: '/request-type'
      fullPath: '/request-type'
      preLoaderRoute: typeof RequestTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-parcel-form': {
      id: '/send-parcel-form'
      path: '/send-parcel-form'
      fullPath: '/send-parcel-form'
      preLoaderRoute: typeof SendParcelFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClientHomeRoute: ClientHomeRoute,
  DriverControlCenterRoute: DriverControlCenterRoute,
  DriverDashboardRoute: DriverDashboardRoute,
  DriverHomeRoute: DriverHomeRoute,
  FoodOrderFormRoute: FoodOrderFormRoute,
  LoginRoute: LoginRoute,
  OrderHistoryRoute: OrderHistoryRoute,
  PartnerDashboardRoute: PartnerDashboardRoute,
  PaxiFormRoute: PaxiFormRoute,
  PaxiReceiveRoute: PaxiReceiveRoute,
  PaxiSendRoute: PaxiSendRoute,
  ReceiveParcelFormRoute: ReceiveParcelFormRoute,
  RequestTypeRoute: RequestTypeRoute,
  ReviewsRoute: ReviewsRoute,
  SendParcelFormRoute: SendParcelFormRoute,
  TrackOrderRoute: TrackOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
